apiVersion: apps/v1
kind : Deployment
metadata: 
    name: utilize-deployment
spec:
   replicas: 2
   selector:
        matchLabels: 
           app: utilize-app
   template:
        metadata:
            labels:
              app: utilize-app
        spec:
          containers:
             - name: utilize-app      
               image : rohit9911/utilize-app:latest 
               ports:
                  - containerPort: 5000
               livenessProbe:
                      httpGet:
                          path: /
                          port: 5000
                      initialDelaySeconds: 10
                      periodSeconds: 10

               readinessProbe:
                      httpGet:
                          path: /
                          port: 5000
                      initialDelaySeconds: 5
                      periodSeconds: 5   
               resources:
                requests:
                      cpu: "100m"
                      memory: "128Mi"
                limits:
                    cpu: "500m"
                    memory: "256Mi"