apiVersion: v1
kind: Service
metadata:
  name: utilize-svc
spec:
   type: NodePort 
   selector:
        app: utilize-app        # Must match the labels on your pods
   ports:
    - nodePort: 30007
      port: 5000     # Port exposed by the service inside the cluster
      targetPort: 5000 # Port the container is actually listening on